### ISSUE TITLE
cloning workflow

### ISSUE THREAD

**Issue by pahosler** [cpp-gamedev/blog#8]
### issue concerning workflow

The theme isn't in master causing the downstream theme folder to be empty.
The result is, needing to find the notepadium theme and install it. It would be best to eliminate that step, it's not obvious that it needs to be done.

Locally I had to change two lines in `public/index.xml` due to renaming the february-challenges markdown file to index.md., and a `server -D` did not rebuild. I don't know if it might cause an issue with the published blog site. The lines are identical so I'll only paste one of them.

in both `<link>` and `<guid>` under February Challenges:
`https://cpp-gamdev.netlify.com/posts/february-challenges/feb-2020-challenges/`
should be changed to
`https://cpp-gamdev.netlify.com/posts/february-challenges/`

**Comment by mdaffin** [comment]
Sorry, the theme was added as a submodule and needs a `git submodule update --init --recursive` after cloning. Really need to add a readme to make this clearer.
